[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
coston = "${COSTON_RPC_URL}"
coston2 = "${COSTON2_RPC_URL}"
songbird = "${SONGBIRD_RPC_URL}"
flare = "${FLARE_RPC_URL}"

[etherscan]
coston = { key = "${FLARE_RPC_API_KEY}", chain = 16, url = "${COSTON_RPC_URL}" }
coston2 = { key = "${FLARE_RPC_API_KEY}", chain = 114, url = "${COSTON2_RPC_URL}" }
songbird = { key = "${FLARE_RPC_API_KEY}", chain = 19, url = "${SONGBIRD_RPC_URL}" }
flare = { key = "${FLARE_RPC_API_KEY}", chain = 14, url = "${FLARE_RPC_URL}" }